[package]
name = "weecord"
version = "0.1.0"
authors = ["Porter Smith <flowbish@gmail.com>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[lib]
name = "weecord"
crate-type = ["dylib"]

[dependencies]
