[package]
name = "weecord"
version = "0.1.0"
authors = ["Porter Smith <flowbish@gmail.com>", "khyperia <khyperia@live.com>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3"
pkg-config = "*"

[lib]
name = "weecord"
crate-type = ["dylib"]

[dependencies]
#discord = "^0.5.0"
discord = { git = "https://github.com/SpaceManiac/discord-rs.git" }
regex = "0.1"
libc = "0.2.0"
